[package]
name = "voidtui"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
unicode-width = "0.2.0"
unicode-segmentation = "1.12.0"
winapi = "0.3.9"
winver = "1.0.0"

[[example]]
name = "app"
path = "examples/app.rs"